version: "3.3"
services:
  ecollect:
    image: migutak/ecollect:1.0.0
    container_name: ecollect
    restart: always
    ports:
      - "80:80"
    networks:
    - ecol-network

  ecollect_apis:
    image: migutak/ecollect_apis:1.0.0
    container_name: ecollect_apis
    restart: always
    environment:
      - DB_HOST=dbsvr2dr
      - DB_PORT=1521
      - DB_USER=ecol
      - DB_PASSWORD=ecol
      - DB_DATABASE=ecoltst
    ports:
      - "8000:8000"
    networks:
    - ecol-network

  oracledb_node:
    image: migutak/oracledbnode:1.0.0
    container_name: oracledb_node
    restart: always
    environment:
      - DB_USER=ecol
      - DB_PASSWORD=ecol
      - DB_CONNECTIONSTRING=dbsvr2dr:1521/ecoltst
    ports:
      - "6001:6001"
    networks:
    - ecol-network

  uploads:
    image: migutak/uploads:1.0.0
    container_name: uploads
    restart: always
    environment:
      - CORS=http://ecollecttst.co-opbank.co.ke
      - DB_USER=ecol
      - DB_PASSWORD=ecol
      - DB_CONNECTIONSTRING=dbsvr2dr:1523/ecoltst
    volumes:
      - /app/uploads:/var/uploads
    ports:
      - "4000:4000"
      - "5000:5000"
      - "5001:5001"
      - "3000:3000"
    networks:
    - ecol-network

  docxletters:
    image: migutak/docxletters:1.0.0
    container_name: docx
    restart: always
    volumes:
      - /app/demands:/app/demands
    environment:
      - FILEPATH=/app/demands/
      - IMAGEPATH=/app/docxletters/routes/
    ports:
      - "8004:8004"
    networks:
    - ecol-network

  grids_viewall:
    image: migutak/grids_viewall:1.0.0
    container_name: grids_viewall
    restart: on-failure
    environment:
      - DB_USER=ecol
      - DB_PASSWORD=ecol
      - DB_CONNECTIONSTRING=dbsvr2dr:1523/ecoltst
      - LICENSE='MjAwMDAwMDAwMDAwMA==598447838c89eb4366146127615e40a4',
      - APPLINK=http://ecollecttst.co-opbank.co.ke    
    ports:
      - "9000:4000"
    networks:
    - ecol-network

  birt:
    container_name: birt
    image: migutak/birt:1.0.0
    volumes:
      - /app/birt/reports:/usr/local/tomcat/webapps/birt
    restart: always
    ports:
      - 8787:8080

networks:
  ecol-network:
    driver: bridge