export const environment = {
  production: true,
  adlogin: false,
  api: 'http://e87995f7.ngrok.io',
  mongo: 'https://ecollecttst.co-opbank.co.ke',
  nodeapi: 'http://e87995f7.ngrok.io',
  letters_path: 'c:\\logs\\',
  letters_api: 'http://e87995f7.ngrok.io/docx/',
  uploadurl: 'http://e87995f7.ngrok.io/filesapi',
  demanddownload: 'http://e87995f7.ngrok.io/demanddownload',
  valor: 'http://e87995f7.ngrok.io/valor',
  metrics: 'https://ecollecttst.co-opbank.co.ke/appmetrics-dash',
  applink: 'http://e87995f7.ngrok.io',
  xlsuploadapi: 'http://e87995f7.ngrok.io/xlsupload/',
  xlstemplate: 'C:\\Users\\Kevin\\Documents\\upload_notes.xlsx',
  emailapi: 'http://ecollecttst.co-opbank.co.ke/demandemail/email',
  auth: 'http://ecollecttst.co-opbank.co.ke/adlogin',
  filesapi: 'http://e87995f7.ngrok.io/filesapi',
  accplanlink: 'http://e87995f7.ngrok.io/accplanlink',
  kibanarpt: 'http://ecollecttst.co-opbank.co.ke:5601',
  manuals_path: 'C:\\Users\\Kevin\\Documents\\ecol_manuals\\',
  birt: 'http://e87995f7.ngrok.io/birt',
  kibana: 'http://ecollecttst.co-opbank.co.ke:5601/app/kibana#/dashboard?_g=0',
};

