export const environment = {
  production: true,
  adlogin: false,
  api: 'https://ecollecttest.co-opbank.co.ke',
  mongo: 'https://ecollecttest.co-opbank.co.ke',
  nodeapi: 'https://ecollecttest.co-opbank.co.ke/nodeapi',
  letters_path: 'c:\\logs\\demands\\',
  letters_api: 'https://ecollecttest.co-opbank.co.ke/docx/',
  uploadurl: 'https://ecollecttest.co-opbank.co.ke/upload',
  demanddownload: 'https://ecollecttest.co-opbank.co.ke/demanddownload',
  valor: 'https://ecollecttest.co-opbank.co.ke/valor',
  metrics: 'https://ecollecttest.co-opbank.co.ke/appmetrics-dash',
  applink: 'https://ecollecttest.co-opbank.co.ke',
  xlsuploadapi: 'https://ecollecttest.co-opbank.co.ke/xlsupload/',
  xlstemplate: 'C:\\Users\\Kevin\\Documents\\upload_notes.xlsx',
  emailapi: 'https://ecollecttest.co-opbank.co.ke/demandemail/email',
  demandsmsapi: "https://rest.nexmo.com/sms/json",
  auth: 'https://ecollecttest.co-opbank.co.ke/adlogin',
  filesapi: 'https://ecollecttest.co-opbank.co.ke/filesapi',
  accplanlink: 'http://ecollecttest.co-opbank.co.ke:3001',
  kibanarpt: 'http://ecollecttest.co-opbank.co.ke:5601',
  manuals_path: 'C:\\Users\\Kevin\\Documents\\ecol_manuals\\',
  birt: 'http://ecollecttest.co-opbank.co.ke:8787/birt',
  kibana: 'http://ecollecttest.co-opbank.co.ke:5601/app/kibana#/dashboard?_g=0',
  secret: "123#Today"
};
