export const environment = {
  production: true,
  adlogin: true,
  api: 'https://ecollectweb.co-opbank.co.ke',
  nodeapi: 'https://ecollectweb.co-opbank.co.ke/loans',
  letters_path: '/home/ecollectadmin/demand_letters/',
  letters_api: 'https://ecollectweb.co-opbank.co.ke/docx/',
  // uploadurl: 'https://ecollectweb.co-opbank.co.ke/upload',
  uploadurl: 'https://ecollectweb.co-opbank.co.ke/filesapi',
  valor: 'https://ecollectweb.co-opbank.co.ke/valor',
  metrics: 'https://ecollectweb.co-opbank.co.ke/appmetrics-dash',
  applink: 'https://ecollectweb.co-opbank.co.ke',
  xlsuploadapi: 'https://ecollectweb.co-opbank.co.ke/xlsupload/',
  xlstemplate: '/home/ecollectadmin/templates/upload_notes.xlsx',
  emailapi: 'https://ecollectweb.co-opbank.co.ke/demandemail/email/send',
  auth: 'https://ecollectweb.co-opbank.co.ke/adlogin',
  filesapi: 'https://ecollectweb.co-opbank.co.ke/filesapi',
  accplanlink: 'http://ecollectapp.co-opbank.co.ke:3001',
  kibanarpt: 'http://ecollectweb.co-opbank.co.ke:5601',
  manuals_path: '/app/manuals/',
  birt: 'http://ecollectweb.co-opbank.co.ke:8787/birt',
};
