export const environment = {
  production: true,
  adlogin: false,
  api: 'https://ecollecttest.co-opbank.co.ke',
  mongo: 'https://ecollecttest.co-opbank.co.ke',
  nodeapi: 'https://ecollecttest.co-opbank.co.ke/nodeapi',
  letters_path: 'c:\\logs\\demands\\',
  letters_api: 'https://ecollecttest.co-opbank.co.ke/docx/',
  uploadurl: 'https://ecollecttest.co-opbank.co.ke/upload',
  demanddownload: 'https://ecollecttest.co-opbank.co.ke/demanddownload',
  valor: 'https://ecollecttest.co-opbank.co.ke/valor',
  metrics: 'https://ecollecttest.co-opbank.co.ke/appmetrics-dash',
  applink: 'https://ecollecttest.co-opbank.co.ke',
  xlsuploadapi: 'https://ecollecttest.co-opbank.co.ke/xlsupload/',
  xlstemplate: 'C:\\Users\\Kevin\\Documents\\upload_notes.xlsx',
  emailapi: 'https://ecollecttest.co-opbank.co.ke/demandemail/email',
  demandsmsapi: "https://rest.nexmo.com/sms/json",
  auth: 'https://ecollecttest.co-opbank.co.ke/adlogin',
  filesapi: 'https://ecollecttest.co-opbank.co.ke/filesapi',
  accplanlink: 'http://ecollecttest.co-opbank.co.ke:3001',
  kibanarpt: 'http://ecollecttest.co-opbank.co.ke:5601',
  manuals_path: 'C:\\Users\\Kevin\\Documents\\ecol_manuals\\',
  birt: 'http://ecollecttest.co-opbank.co.ke:8787/birt',
  kibana: 'http://ecollecttest.co-opbank.co.ke:5601/app/kibana#/dashboard?_g=0',
  accplanreport: 'http://172.16.19.151:5601/app/kibana#/discover/346b8c30-0b89-11ea-8410-c5d8870411ab?_g=()',
  ptpreport: 'http://172.16.19.151:5601/app/kibana#/discover/6f42b0b0-0b8c-11ea-8410-c5d8870411ab?_g=(refreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-1y%2Cto%3Anow))'
};
