export const environment = {
  production: true,
  adlogin: false,
  api: 'http://ecollecttst.co-opbank.co.ke:8000',
  mongo: 'http://ecollecttst.co-opbank.co.ke',
  nodeapi: 'http://ecollecttst.co-opbank.co.ke:6000/nodeapi',
  letters_path: '/home/ecollectadmin/demand_letters/',
  letters_api: 'http://ecollecttst.co-opbank.co.ke:8004/docx/',
  uploadurl: 'http://ecollecttst.co-opbank.co.ke/filesapi',
  demanddownload: 'http://ecollecttst.co-opbank.co.ke/demanddownload',
  valor: 'http://ecollecttst.co-opbank.co.ke/valor',
  metrics: 'http://ecollecttst.co-opbank.co.ke/appmetrics-dash',
  applink: 'http://ecollecttst.co-opbank.co.ke',
  xlsuploadapi: 'http://ecollecttst.co-opbank.co.ke/xlsupload/',
  xlstemplate: '/home/ecollectadmin/templates/upload_notes.xlsx',
  emailapi: 'http://ecollecttst.co-opbank.co.ke/demandemail/email',
  auth: 'http://ecollecttst.co-opbank.co.ke/adlogin',
  filesapi: 'http://ecollecttst.co-opbank.co.ke/filesapi',
  accplanlink: 'http://ecollectapp.co-opbank.co.ke:3001',
  kibanarpt: 'http://ecollecttst.co-opbank.co.ke:5601',
  manuals_path: '/app/manuals/',
  birt: 'http://ecollecttst.co-opbank.co.ke:8787/birt',
  kibana: 'http://ecollecttst.co-opbank.co.ke:5601/app/kibana#/dashboard?_g=0',
};
