export const environment = {
  production: true,
  adlogin: true,
  api: 'https://ecollectweb.co-opbank.co.ke',
  letters_path: '/home/ecollectadmin/demand_letters/',
  letters_api: 'https://ecollectweb.co-opbank.co.ke/docx/',
  uploadurl: 'https://ecollectweb.co-opbank.co.ke/upload',
  valor: 'https://ecollectweb.co-opbank.co.ke/valor',
  metrics: 'https://ecollectweb.co-opbank.co.ke/appmetrics-dash',
  applink: 'https://ecollectweb.co-opbank.co.ke',
  xlsuploadapi: 'https://ecollectweb.co-opbank.co.ke/xlsupload/',
  xlstemplate: '/home/ecollectadmin/templates/upload_notes.xlsx',
  emailapi: 'https://ecollectweb.co-opbank.co.ke/demandemail',
  auth: 'https://ecollectweb.co-opbank.co.ke/adlogin',
  filesapi: 'https://ecollectweb.co-opbank.co.ke/filesapi',
  accplanlink: 'https://ecollectweb.co-opbank.co.ke/accplan',
  kibanarpt: 'http://ecollectweb.co-opbank.co.ke:5601',
  manuals_path: '/home/ecollectadmin/app/manuals/',
  birt: 'http://172.16.204.37:8080/birt',
};
